name: 'Static Cloud Site - Backend'

on:
  push:
    branches:
      - '**'
    pull_request:

jobs:
  unit_tests:
    name: 'Unit Tests'
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'actions/checkout'
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        working-directory: ./functions
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install coverage

      - name: 'Run tests'
        run: |
          coverage run test_main.py
          coverage report -m --fail-under=100

  cloud_functions:
    name: 'Upload Cloud Functions'
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'actions/checkout'
        uses: actions/checkout@v1

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: "Deploy Firebase Functions"
        working-directory: ./functions
        run: |
          npm install -g firebase-tools
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          firebase deploy --only functions --non-interactive --debug
