name: 'Static Cloud Site - Backend'

on:
  push:
    branches:
      - '**'
    pull_request:

jobs:
  unit_tests:
    name: 'Unit Tests'
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'actions/checkout'
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        working-directory: ./functions
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Run tests'
        run: python test_main.py